# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"NUMBERS_STOPWORDS": "10_tokenizer.ipynb",
         "prepare_stopwords": "10_tokenizer.ipynb",
         "tokenize_one": "10_tokenizer.ipynb",
         "get_nodes_for_ntlk": "10_tokenizer.ipynb",
         "tokenize_by_nltk": "10_tokenizer.ipynb",
         "tokenize": "10_tokenizer.ipynb",
         "parallel": "20_utils.ipynb",
         "num_cpus": "20_utils.ipynb",
         "open_file": "20_utils.ipynb",
         "chunk_of_text": "20_utils.ipynb",
         "get_file_chunks": "20_utils.ipynb",
         "tokenize_file": "30_main.ipynb",
         "train_model": "30_main.ipynb",
         "similars_tree_from_model": "30_main.ipynb",
         "get_similars": "30_main.ipynb",
         "similars_tree": "30_main.ipynb"}

modules = ["tokenizer.py",
           "utils.py",
           "main.py"]

doc_url = "https://dperezrada.github.io/keywords2vec/"

git_url = "https://github.com/dperezrada/keywords2vec/tree/master/"

def custom_doc_links(name): return None